### ISSUE TITLE
A way to handle null byte better

### ISSUE THREAD

**Issue by Gouthamve** [cznic/golex#11]
Hi, we are using golex in [prometheus](https://github.com/prometheus/prometheus) instead of the previous hand-written parser and the performance benefit has been amazing.

But we need to support null-bytes `\0` in the text being parsed. For example, we need to be able to parse `<string>{<string>="<string-with-null-byte>"}`

But because we use `\0` for EOF, we are not able to do it. For example: `<string>{<string>="` results in an infinite loop as we added `\0` as a special character for that state [here](https://github.com/prometheus/prometheus/blob/dev-2.0/pkg/textparse/lex.l#L94).

Do you have any ideas as to how we can handle null-byte better?

/cc @fabxc

**Comment by cznic** [comment]
> Hi, we are using golex in prometheus instead of the previous hand-written parser and the performance benefit has been amazing.

Glad to hear! Do you have some numbers to share?

> But we need to support null-bytes \0 in the text being parsed. 

Maybe you can use the [lex library](https://godoc.org/github.com/cznic/golex/lex) and use character classes to map EOF to a character class of its own, like for example [here](https://github.com/cznic/cc/blob/cb9c6524b77e09c333038c6daefbb38cf6e1c20f/encoding.go#L532). Feel free to ask me on things that are not documented clearly enough.

I haven't tried, but maybe in this case a simpler solution can work. Move [this line](https://github.com/prometheus/prometheus/blob/24e9deac71d26a9db5d635df0865b83bd5ff9370/pkg/textparse/lex.l#L68) so it becomes the last rule - they are considered in order of appearance. I'm not sure if it solves the issue, but at least it's easy to try it ;-)

**Comment by Gouthamve** [comment]
Sorry for the late reply, let me explain it better:

So we are now allowing any number of `\0` after the `"` (in <string-with-null-byte>), for example `a{b="a\0c"}` and `a{b="a\0\0c"}` are both valid. Now take this string: `a{b="d`, after `d` is read, `next()` will always return `0` but the lexer tries to consume as many `\0` so it keeps calling `next()` without terminating.

I think using classes would fix it and `lex. RuneEOF` is mapped to -1, but I think it would complicate it from the current system a fair bit. I did not have enough time to look at it today, but will take another look tomorrow and update here.

**Comment by Gouthamve** [comment]
I kinda hacked it in for now :) Made sure that `c.next()` eats up the null-byte rather than expose it to the lexer/parser.

Ref: https://github.com/prometheus/prometheus/pull/2915/files#diff-04e1328eadf10e9e126988700965fc7f

**Comment by cznic** [comment]
> I kinda hacked it in for now :) Made sure that c.next() eats up the null-byte rather than expose it to the lexer/parser.

If it's a correct solution then it's a good one ;-)

Later I realized that there's another possibility, provided you handle UTF-8 input. There are several bytes which can never legaly appear in UTF-8, like 0xFF and all other red cells in [this table](https://en.wikipedia.org/wiki/UTF-8#Codepage_layout), so it's safe to remap EOF to one of those bytes. Unless you need to somehow continue processing input past any invalid UTF-8 sequence as well (compilers might do that, for example).

**Comment by cznic** [comment]
@Gouthamve  I see the PR is already merged, I assume there's nothing left to do here. Feel free to repoen if you think otherwise.
