### ISSUE TITLE
Parsing character by character?

### ISSUE THREAD

**Issue by corywalker** [cznic/golex#13]
Is it possible to get golex/goyacc to parse a document character by character? For context, I am trying to get my parser to ignore whitespace unless we have a newline after a valid statement. For example, assume we have the following file:

    a = b

    a = 
    b

If we parse this by character, we should be able to check after each character if the statement is valid (perhaps if the stack is empty). A hack would be to try parsing more and more lines until we get a valid statement, but this duplicates a lot of parsing. Any ideas?

**Comment by cznic** [comment]
@corywalker 

I've prepared an experimental branch `follow-sets` of goyacc with the following changes:

- Parser state number is available in `lval.yys`, in `yylex.Lex(lval *yySymType).`
- Follow sets are generated using the `-fs` option and are accessible in the `%vFollow` table. %v is the parser prefix, default is `yy`. Its type is `[][]int`. The outer index is the state number, the row is a slice of symbol values accepted in that particular state (includes also non-terminals.) The symbol value is for example `LPAREN` or '(' or whatever was used to declare/define the terminal in the .y file.

How I think it could be used in `yylexer.Lex(lval)`:

```go
func Lex(lval *yySymType) int {
more:
        // Prepare the token as usual.
        // Note: '\n` must be an accepted token of the .l grammar.
        ...
        if tok == '\n' {
                for _, v := range yyFollow[lval.yys] {
                        // yyEofCode is defined in foo.go generated from foo.y.
                        // It represents the predeclared $end terminal.
                        if v == yyEofCode { 
                                return -1 // Parser will accept $end, signal EOF
                        }
                }

                // Parser does not accept $end in this state.
                // The input cannot be complete.
                // Skip the newline.
                goto more
        }

        return tok
}
```
Not tested at all. If you would like to try this, please provide feedback and I'l try to fix problems you may run into. If the solution eventually becomes acceptable for you, I'll merge the `follow-sets` branch to master.

**Comment by corywalker** [comment]
I've made a branch of the same name in expreduce where I am making my grammar compatible with your version of goyacc. Turns out I was using the go tools version. Seems like yours has a lot more features, and if it supports follow sets, then that is a big deal for the project.

Regardless, I found something during the conversion that I think may be related to https://github.com/cznic/goyacc/issues/11. My commit 05c63d12260c692677c7c6caa87895cd0c0ab4b0 should be sufficient to reproduce. I had generated interp.go and a single test case out of the thousands failed. I generated the parser again and another test failed! Then I generated a third time and no tests failed. Whenever I see unexpected indeterminism in Go, my first thought is the use of maps. So perhaps there is another map range that causes tokens to have different precedences each time.

This is probably a non-issue for well-defined grammars. I think mine has a lot of issues/conflicts that are most likely creating some unknown cases for the parser.

Thanks for the help so far!

**Comment by cznic** [comment]
Thanks for the feedback! I'll investigate the goyacc fail when time permits. I'll try first to look at the conflicts and whether there's some easy way to get rid of them. Unfortunately I'm not familiar with the Wolfram language.

**Comment by cznic** [comment]
Note on conflicts: A couple of S/R conflicts may appear in completely valid grammars, they're just then sensitive to the order of the rules in the .y file, otherwise it's not a big deal. R/R conflicts, OTOH, are IMO never okay, because that means the grammar is ambiguous. There are 200+ conflicts in the grammar, that's too much for me to try fix. I'm afraid rewriting the grammar from scratch is probably less work, but still out of my reach for working days.

I'll at least try to fix the goyacc instability now.

**Comment by cznic** [comment]
I believe cznic/goyacc#24 is now fixed. Please try `go get -u github.com/cznic/goyacc`.

----

Recommended read: [R/R conflicts](http://www.gnu.org/software/bison/manual/html_node/Reduce_002fReduce.html).

**Comment by cznic** [comment]
@corywalker I believe this was resolved long ago. Feel free to reopen of you think otherwise.
