### ISSUE TITLE
Install fail...

### ISSUE THREAD

**Issue by peteArnt** [cznic/golex#14]
On my 64-bit Intel Linux box, I get the following error messages while attempting to install golex
**$ go get github.com/cznic/golex
# github.com/cznic/golex
../mygo/src/github.com/cznic/golex/render.go:33:6: l.YYM undefined (type *lex.L has no field or method YYM)
../mygo/src/github.com/cznic/golex/render.go:234:10: l.YYM undefined (type *lex.L has no field or method YYM)
../mygo/src/github.com/cznic/golex/render.go:255:13: l.YYM undefined (type *lex.L has no field or method YYM)
../mygo/src/github.com/cznic/golex/render.go:257:23: l.YYM undefined (type *lex.L has no field or method YYM)**
****
Can anyone provide guidance?  Am I doing something wrong?
-Pete

**Comment by cznic** [comment]
Please try adding the -u flag if it makes any difference?

**Comment by peteArnt** [comment]
Ah, yes. That worked.  I read the docs regarding -u flag.  Thanks for the assist.
