### ISSUE TITLE
Help to compile the file project /cznic/golex/calc

### ISSUE THREAD

**Issue by jcgi** [cznic/golex#8]
Hi, Nice to meet you, I am student at University of San Luis Potosi, actually i am programmer in language GOLANG but i have a problem when i try to compile a projet file github.com/cznic/golex/calc because i cant to compile with the command

calc.go:calc.y
# double gofmt due to it not being idempotent
go tool yacc -o /dev/stdout $< | gofmt | gofmt > $@

I try with other options to compile but no generate a executable file.

You can to explainme how to other options to compile this file please.

Thanks for you comprension.
Regards

**Comment by cznic** [comment]
```bash
jnml@4670:~/src/github.com/cznic/golex/calc$ ll
celkem 44
-rw-r--r-- 1 jnml jnml  1195 pro 12  2014 calc.y
-rw-r--r-- 1 jnml jnml 22962 pro 12  2014 fdl-1.3
-rw-rw-r-- 1 jnml jnml   123 úno 18 23:39 log
-rw-rw-r-- 1 jnml jnml   448 úno 18 23:39 Makefile
-rw-r--r-- 1 jnml jnml  1435 pro 12  2014 README
-rw-r--r-- 1 jnml jnml  1242 pro 12  2014 tokenizer.l
jnml@4670:~/src/github.com/cznic/golex/calc$ make
go tool yacc -o calc.go calc.y
golex -o tokenizer.go tokenizer.l
gofmt -l -s -w *.go
calc.go
go build calc.go tokenizer.go
jnml@4670:~/src/github.com/cznic/golex/calc$ ll
celkem 2612
-rwxrwxr-x 1 jnml jnml 2607280 úno 18 23:41 calc*
-rw-rw-r-- 1 jnml jnml    9566 úno 18 23:41 calc.go
-rw-r--r-- 1 jnml jnml    1195 pro 12  2014 calc.y
-rw-r--r-- 1 jnml jnml   22962 pro 12  2014 fdl-1.3
-rw-rw-r-- 1 jnml jnml     123 úno 18 23:39 log
-rw-rw-r-- 1 jnml jnml     448 úno 18 23:39 Makefile
-rw-r--r-- 1 jnml jnml    1435 pro 12  2014 README
-rw-rw-r-- 1 jnml jnml    2468 úno 18 23:41 tokenizer.go
-rw-r--r-- 1 jnml jnml    1242 pro 12  2014 tokenizer.l
-rw-rw-r-- 1 jnml jnml    3210 úno 18 23:41 y.output
jnml@4670:~/src/github.com/cznic/golex/calc$ 
```

**Comment by questionpython** [comment]
>guest@system:~/go/src/github.com/cznic/golex$ ll
total 72
drwxr-xr-x  7 guest guest 4096 Mar 10 01:36 ./
drwxr-xr-x 12 guest guest 4096 Mar 10 01:35 ../
-rw-r--r--  1 guest guest  265 Mar  9 23:22 all_test.go
-rw-r--r--  1 guest guest  379 Mar  9 23:22 AUTHORS
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 calc/
-rw-r--r--  1 guest guest  299 Mar  9 23:22 CONTRIBUTORS
-rw-r--r--  1 guest guest 5676 Mar  9 23:22 doc.go
drwxr-xr-x  2 guest guest 4096 Mar 10 01:39 example/
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 example2/
drwxr-xr-x  8 guest guest 4096 Mar 10 22:59 .git/
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 lex/
-rw-r--r--  1 guest guest 1483 Mar  9 23:22 LICENSE
-rw-r--r--  1 guest guest 3065 Mar  9 23:22 main.go
-rw-r--r--  1 guest guest  468 Mar  9 23:22 Makefile
-rw-r--r--  1 guest guest  268 Mar  9 23:22 README
-rw-r--r--  1 guest guest 6570 Mar  9 23:22 render.go
guest@system:~/go/src/github.com/cznic/golex$ make
go fmt
go test -i
go test
PASS
ok  	github.com/cznic/golex	0.002s
go install
make todo
make[1]: Entering directory '/home/guest/go/src/github.com/cznic/golex'
lex/example_test.go:148:	_ = yyrule
all_test.go:12:	t.Log("TODO") //TODO
lex/all_test.go:36:func TODO(...interface{}) string {
lex/all_test.go:38:	return fmt.Sprintf("TODO: %s:%d:\n", path.Base(fn), fl)
lex/all_test.go:46:	t.Logf("TODO")
lex/all_test.go:20:	fmt.Fprintln(os.Stderr)
lex/all_test.go:23:	fmt.Fprintln(os.Stderr)
lex/all_test.go:33:	fmt.Fprintln(os.Stderr)
main.go:86:		fmt.Fprintln(stderr, "  If no in_name is given then read from stdin.")
main.go:150:		fmt.Fprintln(os.Stderr, l.String())
make[1]: Leaving directory '/home/guest/go/src/github.com/cznic/golex'
guest@system:~/go/src/github.com/cznic/golex$ ll
total 72
drwxr-xr-x  7 guest guest 4096 Mar 10 01:36 ./
drwxr-xr-x 12 guest guest 4096 Mar 10 01:35 ../
-rw-r--r--  1 guest guest  265 Mar  9 23:22 all_test.go
-rw-r--r--  1 guest guest  379 Mar  9 23:22 AUTHORS
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 calc/
-rw-r--r--  1 guest guest  299 Mar  9 23:22 CONTRIBUTORS
-rw-r--r--  1 guest guest 5676 Mar  9 23:22 doc.go
drwxr-xr-x  2 guest guest 4096 Mar 10 01:39 example/
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 example2/
drwxr-xr-x  8 guest guest 4096 Mar 10 22:59 .git/
drwxr-xr-x  2 guest guest 4096 Mar  9 23:22 lex/
-rw-r--r--  1 guest guest 1483 Mar  9 23:22 LICENSE
-rw-r--r--  1 guest guest 3065 Mar  9 23:22 main.go
-rw-r--r--  1 guest guest  468 Mar  9 23:22 Makefile
-rw-r--r--  1 guest guest  268 Mar  9 23:22 README
-rw-r--r--  1 guest guest 6570 Mar  9 23:22 render.go

how fix?

**Comment by cznic** [comment]
@questionpython 

> but go tool yacc... not work.

That issue was answered today in cznic/goyacc#23. You have to Invoke `goyacc` directly, the `go` tool no more supports that subcommand.
