### ISSUE TITLE
Is golex going to support case-insensitive as flex

### ISSUE THREAD

**Issue by buptmiao** [cznic/golex#9]
I think this feature is very usefull.

**Comment by cznic** [comment]
It is useful. For example [here](https://github.com/cznic/ql/blob/7a63cd7aa46ecd9f549b96983029576af2178f60/scanner.l#L112).

**Comment by buptmiao** [comment]
Thanks. I saw this work around, but it is too boring if there are too many reserved words.

**Comment by cznic** [comment]
Quoting an answer from [stackoverflow](http://stackoverflow.com/a/22687275)

> You could set case-insensitivity in the `.l` file:
>
> `%option caseless`
>
> You could call `flex -i`.
>
> Or you could state individual rules to be case-insensitive:
>
> `(?i:word)`

Which of these options would be helpful in your use case?

**Comment by buptmiao** [comment]
this option works in my use case.
```
%option case-insensitive
```

**Comment by cznic** [comment]
@buptmiao Please try checking out `cznic/lex` branch `case-insensitive`, then rebuild `cznic/golex` and test with some `.l` source. I did not actually tested if it works whatsoever, so please provide feedback. Thank you.

**Comment by buptmiao** [comment]
You are so great! It works now.

**Comment by cznic** [comment]
Thanks for testing it!
